name: android_studio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Navigation & State Management
  go_router: ^17.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.1

  # Networking & Socket (Modul 4 & 5)
  dio: ^5.9.2
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  logger: ^2.7.0

  # Database Local (Modul 6)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # Native Helper (Modul 7)
  # (Metode MethodChannel sudah ada di flutter/services, tidak butuh package luar tambahan)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Generator & Builder (Wajib ada untuk Isar)
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true