name: UTD Advanced CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengunduh kode proyek ke server virtual
      - name: Download / Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Lingkungan Java JDK 17
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # ==============================================================================
      # PERBAIKAN STABILITAS: Mengubah Teks Base64 menjadi Berkas Fisik Keystore Asli
      # ==============================================================================
      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'upload-keystore.jks'
          fileDir: './android/app/'
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      # 2c. Menyusun Berkas Properti Kunci Digital langsung di folder android/
      - name: Create Key Properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      # 3. Menginstal Flutter SDK Stable
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. Mengunduh dependencies sesuai pubspec.yaml
      - name: Install Dependencies
        run: flutter pub get

      # 5. Membangun ulang file otomatis kode generasi Isar (build_runner)
      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # 6. Menjalankan Uji Otomatis (Unit/Widget Test)
      - name: Run Automated Tests
        run: flutter test

      # 7. Membangun file APK versi Release resmi
      - name: Build APK Release
        run: flutter build apk --release

      # 8. Mengunggah APK ke Halaman GitHub Artifacts
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UTD-Advanced-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk